language: cpp

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev

env:
  global:
    - CC=gcc-4.9
    - CXX=g++-4.9

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - make test