language: cpp

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - libboost1.55-all-dev

install:
  - export CC="gcc-4.9"
  - export CXX="g++-4.9"

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - make test