language: cpp

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - libboost1.55-all-dev


compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=`which g++-4.9` ..
  - make -j4
  - make test