language: cpp

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - libboost1.55-all-dev

env:
  - CC=gcc-4.9
  - CXX=g++-3.3

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - make test